packages:
  - ./packages/**
  - ./tests/**

catalogs:
  dev:
    '@types/node': '26.4.0'
    'oxfmt': '0.66.0'
    'oxlint': '1.81.0'
    'oxlint-tsgolint': '7.0.2001'
  peer:
    'oxfmt': '>=0.66.0 <1'
    'oxlint': '>=1.80.0 <2'
    'oxlint-tsgolint': '>=7.0.2001 <8'
