name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

env:
  HUSKY: 0
  CI: true

jobs:
  test:
    name: Test (Node ${{ matrix.node }})

    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        node:
          - 24
          - 26

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@e3b04865510c657477cc722854b31a3b74c72c09 # v2.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: Run build
        run: pnpm run build

      - name: Run test
        run: pnpm run test

      - name: Ensure proper oxlint config rules
        run: pnpm --filter="@marcalexiei/oxlint-config" run rules:check

  code-checks:
    name: Code checks

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Dependencies
        uses: marcalexiei/github-actions/setup-node-and-pnpm@e3b04865510c657477cc722854b31a3b74c72c09 # v2.2.0

      - name: Typecheck
        run: pnpm run typecheck

      - name: Format
        run: pnpm run format

      # - name: Lint
      #   run: pnpm run lint

  ci-ok:
    name: CI OK
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs:
      - test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
